<x-asset-link src="assets/js/vendor/jquery.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/jquery.zoom.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/aos.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/swiper-bundle.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/smoothscroll.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/countdownTimer.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/owl.carousel.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/slick.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/vendor/jquery-range-ui.min.js" type="js"></x-asset-link>
<x-asset-link src="assets/js/main.js" type="js"></x-asset-link>
